//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMANOMINA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_RESPONSABLES
    {
        public int ID_EMPLEADO { get; set; }
        public string COD_EMPLEADO { get; set; }
        public string NOMBRE_EMPLEADO { get; set; }
        public decimal SALARIO_MENSUAL_EMPLEADO { get; set; }
        public string NOMBRE_DEPARTAMENTO { get; set; }
        public bool RESPONSABLE_AREA { get; set; }
    }
}
