//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMANOMINA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISTEMA_DE_NOMINAEntities : DbContext
    {
        public SISTEMA_DE_NOMINAEntities()
            : base("name=SISTEMA_DE_NOMINAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<MOVIMIENTO_EMPLEADO> MOVIMIENTO_EMPLEADO { get; set; }
        public virtual DbSet<NIVEL_RIESGO> NIVEL_RIESGO { get; set; }
        public virtual DbSet<PUESTO> PUESTO { get; set; }
        public virtual DbSet<REGISTRO_TRANSACCION_DEDUCCION> REGISTRO_TRANSACCION_DEDUCCION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_DE_DEDUCCION> TIPO_DE_DEDUCCION { get; set; }
        public virtual DbSet<Historial_Deducciones> Historial_Deducciones { get; set; }
        public virtual DbSet<EMP_CARGO> EMP_CARGO { get; set; }
        public virtual DbSet<EMP_DEP> EMP_DEP { get; set; }
        public virtual DbSet<EMP_RESPONSABLES> EMP_RESPONSABLES { get; set; }
        public virtual DbSet<PUESTO_RIESGO> PUESTO_RIESGO { get; set; }
        public virtual DbSet<REGISTRO_TRANSACCION_INGRESO> REGISTRO_TRANSACCION_INGRESO { get; set; }
        public virtual DbSet<historial_ingreso> historial_ingreso { get; set; }
        public virtual DbSet<HISTORIAL_EMPLEADO> HISTORIAL_EMPLEADO { get; set; }
    }
}
